### ISSUE TITLE
Modelo relacional BD

### ISSUE THREAD

**Issue by LiderShino1008** [LiderShino1008/Inversiones-GAMA#2]
- [x] Revisar que existan todas las tablas y campos necesarios.
- [x] Revisar las relaciones entre las tablas
- [x] Revisar la nomenclatura **(utilizar nombres nemotécnicos, estilizados y con un estándar para todos y cada uno de los campos de la BD)**

**Comment by Maferamirezz** [comment]
Listo pue, ya wa ver qué onda. :3

**Comment by LiderShino1008** [comment]
Modelo completo 100%
